services:
  - type: web
    name: api-toolkit
    runtime: docker
    dockerfilePath: Dockerfile.light
    plan: free
    envVars:
      - key: API_KEY
        value: "CsSiJoPjB2+1hmLLncCoO1ApAK8XRF4gy+Y6L+jen/w="
      - key: RATE_LIMIT
        value: 100
      - key: HOST
        value: 0.0.0.0
      - key: PORT
        value: 8000
    healthCheckPath: /health
